"""empty message

Revision ID: d151299169cc
Revises: 06c9b4721eb9
Create Date: 2025-08-09 16:05:27.399268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d151299169cc"
down_revision: Union[str, Sequence[str], None] = "06c9b4721eb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_infos",
        "password",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_infos",
        "password",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
